--!strict

local Constants = {
	REMOTES_FOLDER_NAME = "Remotes",
	MARBLE_REMOTE_NAME = "MarbleRequested",
	GALLERY_FOLDER_NAME = "ResonanceGallery",
	STATIC_FOLDER_NAME = "Static",
	ANCHORS_FOLDER_NAME = "Anchors",
	MARBLES_FOLDER_NAME = "Marbles",
	SPAWN_FOLDER_NAME = "Spawn",
	CLIENT_VISUALS_FOLDER_NAME = "ArrayWaveClientVisuals",
	AUDIO_BAND_COUNT = 96,
	VISUAL_BAND_COUNT = 96,
	UI_ANALYZER_BAR_COUNT = 16,
	GALLERY_ANCHOR_GRID_SIZE = 17,
	GRID_SIZE = 21,
	GRID_SPACING = 1.05,
	ROW_BAR_COUNT = 96,
	CIRCLE_BAR_COUNT = 128,
	SHOCKWAVE_POOL_SIZE = 8,
	SHOCKWAVE_SEGMENT_COUNT = 48,
	ACCENT_LIGHT_COUNT = 10,
	MIN_LOADING_TIME = 2,
	MAX_LOADING_TIME = 8,
	MARBLE_COOLDOWN = 0.45,
	MAX_MARBLES_PER_PLAYER = 6,
	MARBLE_LIFETIME = 12,
	MAX_MARBLE_ENERGY = 1,
	DEFAULT_AUDIO_ASSET_ID = "9043887091",
	DEFAULT_AUDIO_LABEL = "Base Song",
	DEFAULT_AUDIO_MODE = "Asset",
	DEFAULT_SENSITIVITY = 1,
	DEFAULT_INTENSITY = 1,
	DEFAULT_VISUAL_STYLE = "Grid",
	UI_PANEL_WIDTH = 336,
	UI_PANEL_MAX_WIDTH_SCALE = 0.2,
	VISUAL_STYLES = { "Grid", "Row", "Circle", "All", "Minimal" },
	PALETTE = table.freeze({
		Background = Color3.fromRGB(5, 7, 10),
		Surface = Color3.fromRGB(12, 16, 22),
		SurfaceRaised = Color3.fromRGB(18, 24, 32),
		Text = Color3.fromRGB(235, 242, 248),
		TextMuted = Color3.fromRGB(136, 150, 162),
		Cyan = Color3.fromRGB(80, 220, 255),
		CyanSoft = Color3.fromRGB(118, 232, 255),
		Amber = Color3.fromRGB(255, 190, 95),
		Stroke = Color3.fromRGB(58, 75, 88),
		Charcoal = Color3.fromRGB(12, 16, 22),
		Graphite = Color3.fromRGB(22, 29, 37),
		SoftWhite = Color3.fromRGB(235, 242, 248),
	}),
}

return table.freeze(Constants)
