--!strict

local Constants = {
	REMOTES_FOLDER_NAME = "Remotes",
	MARBLE_REMOTE_NAME = "MarbleRequested",
	GALLERY_FOLDER_NAME = "ResonanceGallery",
	STATIC_FOLDER_NAME = "Static",
	ANCHORS_FOLDER_NAME = "Anchors",
	MARBLES_FOLDER_NAME = "Marbles",
	SPAWN_FOLDER_NAME = "Spawn",
	CLIENT_VISUALS_FOLDER_NAME = "ArrayWaveClientVisuals",
	VISUAL_BAND_COUNT = 32,
	GALLERY_ANCHOR_GRID_SIZE = 17,
	GRID_SIZE = 21,
	GRID_SPACING = 1.15,
	ROW_BAR_COUNT = 64,
	CIRCLE_BAR_COUNT = 96,
	SHOCKWAVE_POOL_SIZE = 6,
	SHOCKWAVE_SEGMENT_COUNT = 48,
	MARBLE_COOLDOWN = 0.45,
	MAX_MARBLES_PER_PLAYER = 6,
	MARBLE_LIFETIME = 12,
	MAX_MARBLE_ENERGY = 1,
	DEFAULT_AUDIO_ASSET_ID = "9043887091",
	DEFAULT_AUDIO_LABEL = "Base Song",
	DEFAULT_AUDIO_MODE = "Asset",
	DEFAULT_SENSITIVITY = 1,
	DEFAULT_INTENSITY = 1,
	DEFAULT_VISUAL_STYLE = "Grid",
	UI_PANEL_WIDTH = 300,
	UI_PANEL_MAX_WIDTH_SCALE = 0.2,
	VISUAL_STYLES = { "Grid", "Row", "Circle", "All", "Minimal" },
	PALETTE = {
		Background = Color3.fromRGB(10, 11, 12),
		Charcoal = Color3.fromRGB(18, 20, 21),
		Graphite = Color3.fromRGB(34, 37, 38),
		SoftWhite = Color3.fromRGB(220, 228, 224),
		Cyan = Color3.fromRGB(104, 190, 194),
		Amber = Color3.fromRGB(212, 180, 116),
	},
}

return table.freeze(Constants)
